#!/usr/bin/env node
'use strict';

// Builds the website version of TextStats into dist-web/ (no npm packages needed).
//
// The website uses the same code as the desktop app:
//   - src/renderer/*        the window (HTML, CSS, app logic, translations)
//   - src/extract/*         the file readers and word classification, bundled into core.js
//   - src/web/*             the browser replacements for the desktop bridge (preload/main)
//
// Usage: node tools/build-web.js [outDir]

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.resolve(process.argv[2] || path.join(ROOT, 'dist-web'));

// Desktop-only modules replaced in the browser.
const SWAP = {
  [path.join(ROOT, 'src/extract/pdf-loader.js')]: path.join(ROOT, 'src/web/pdf-loader-web.js'),
};
// Node built-ins: only reachable from desktop code paths (e.g. extractFile reading a path).
const BUILTINS = new Set(['fs', 'path', 'url', 'zlib', 'worker_threads']);

function resolve(fromFile, id) {
  if (BUILTINS.has(id)) return `builtin:${id}`;
  if (!id.startsWith('.')) throw new Error(`Unexpected package "${id}" required from ${fromFile}`);
  let p = path.resolve(path.dirname(fromFile), id);
  if (fs.existsSync(p + '.js')) p += '.js';
  else if (fs.existsSync(path.join(p, 'index.js'))) p = path.join(p, 'index.js');
  if (!fs.existsSync(p)) throw new Error(`Cannot find ${id} from ${fromFile}`);
  return SWAP[p] || p;
}

// Small CommonJS bundler: wraps every reachable module in a function.
function bundle(entries) {
  const modules = new Map();
  const queue = [...entries];
  while (queue.length) {
    const file = queue.shift();
    if (modules.has(file) || file.startsWith('builtin:')) continue;
    let code = fs.readFileSync(file, 'utf8');
    code = code.replace(/require\((['"])([^'"]+)\1\)/g, (all, q, id) => {
      const target = resolve(file, id);
      queue.push(target);
      return `require(${JSON.stringify(key(target))})`;
    });
    modules.set(file, code);
  }
  const parts = [];
  for (const [file, code] of modules) {
    parts.push(`${JSON.stringify(key(file))}: function (require, module, exports) {\n${code}\n}`);
  }
  return `/* TextStats core (generated by tools/build-web.js from src/extract and src/renderer/wordclasses.js). */
(function () {
  'use strict';
  const defs = {\n${parts.join(',\n')}\n};
  const cache = {};
  function require(id) {
    if (id.startsWith('builtin:')) {
      return new Proxy({}, { get: (t, k) => { throw new Error(id.slice(8) + '.' + String(k) + ' is not available in the browser'); } });
    }
    if (cache[id]) return cache[id].exports;
    const module = (cache[id] = { exports: {} });
    defs[id](require, module, module.exports);
    return module.exports;
  }
  const core = require(${JSON.stringify(key(entries[0]))});
  const lex = require(${JSON.stringify(key(entries[1]))});
  const inflate = require(${JSON.stringify(key(entries[2]))});
  self.TextStatsBundle = {
    extractBuffer: core.extractBuffer,
    parseLexicon: lex.parseLexicon,
    classifyWith: lex.classifyWith,
    gunzip: inflate.gunzip,
  };
})();
`;
}

function key(file) {
  return file.startsWith('builtin:') ? file : path.relative(ROOT, file).split(path.sep).join('/');
}

function copy(src, dest, filter = () => true) {
  const st = fs.statSync(src);
  if (st.isDirectory()) {
    for (const name of fs.readdirSync(src)) copy(path.join(src, name), path.join(dest, name), filter);
  } else if (filter(src)) {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
}

function main() {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  // 1. The window: same files as the desktop app.
  copy(path.join(ROOT, 'src/renderer'), OUT);
  let html = fs.readFileSync(path.join(ROOT, 'src/renderer/index.html'), 'utf8');
  html = html
    .replace('<script src="i18n.js"></script>', '<script src="web-api.js"></script>\n  <script src="i18n.js"></script>')
    .replace('<link rel="stylesheet" href="styles.css" />', '<link rel="icon" type="image/png" href="assets/icon.png" />\n  <link rel="stylesheet" href="styles.css" />')
    .replace('<html lang="en" data-theme="light">', '<html lang="en" data-theme="light" data-platform="web">');
  if (!html.includes('web-api.js')) throw new Error('index.html changed: could not add web-api.js');
  fs.writeFileSync(path.join(OUT, 'index.html'), html);

  // 2. Browser bridge and worker.
  for (const f of ['web-api.js', 'worker.js']) fs.copyFileSync(path.join(ROOT, 'src/web', f), path.join(OUT, f));

  // 3. File readers + word classification, bundled.
  const shim = fs.readFileSync(path.join(ROOT, 'src/web/buffer-shim.js'), 'utf8');
  const core = bundle([
    path.join(ROOT, 'src/extract/index.js'),
    path.join(ROOT, 'src/extract/lexicon-core.js'),
    path.join(ROOT, 'src/extract/inflate.js'),
  ]);
  fs.writeFileSync(path.join(OUT, 'core.js'), shim + '\n' + core);

  // 4. pdf.js and the word lists.
  copy(path.join(ROOT, 'vendor/pdfjs'), path.join(OUT, 'vendor/pdfjs'));
  copy(path.join(ROOT, 'vendor/lexicon'), path.join(OUT, 'vendor/lexicon'), (f) => !f.endsWith('.py'));

  // GitHub Pages: serve files as-is (no Jekyll processing).
  fs.writeFileSync(path.join(OUT, '.nojekyll'), '');

  let files = 0;
  let bytes = 0;
  (function count(d) {
    for (const n of fs.readdirSync(d)) {
      const p = path.join(d, n);
      const st = fs.statSync(p);
      if (st.isDirectory()) count(p);
      else {
        files++;
        bytes += st.size;
      }
    }
  })(OUT);
  console.log(`Website built in ${OUT} (${files} files, ${(bytes / 1048576).toFixed(1)} MB)`);
}

main();
